// This file is auto-generated by `php artisan stimulus:install`
// Run that command whenever you add a new controller or create them with
// `php artisan stimulus:make controllerName`

import { application } from '../libs/stimulus'


import CustomerController from './customer_controller'
application.register('customer', CustomerController)

import EmployeeController from './employee_controller'
application.register('employee', EmployeeController)

import FilterController from './filter_controller'
application.register('filter', FilterController)

import FlashMessageController from './flash_message_controller'
application.register('flash-message', FlashMessageController)

import FooterVisibilityController from './footer-visibility_controller'
application.register('footer-visibility', FooterVisibilityController)

import FormValidationController from './form_validation_controller'
application.register('form-validation', FormValidationController)

import HelloController from './hello_controller'
application.register('hello', HelloController)

import PosController from './pos_controller'
application.register('pos', PosController)

import ProductController from './product_controller'
application.register('product', ProductController)

import ProductSalesController from './product_sales_controller'
application.register('product-sales', ProductSalesController)

import SupplierController from './supplier_controller'
application.register('supplier', SupplierController)

import UserController from './user_controller'
application.register('user', UserController)